# Generated by Django 5.0.3 on 2024-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_image_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_on_index_page',
            field=models.BooleanField(default=True, verbose_name='display'),
        ),
    ]
