# Generated by Django 4.2 on 2024-03-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_display_on_index_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_on_index_page',
        ),
    ]
