# Generated by Django 4.2 on 2024-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_display_on_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_on_index_page',
            field=models.BooleanField(default=True, verbose_name='display'),
        ),
    ]
