# Generated by Django 5.0.2 on 2024-03-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_product_image_alter_product_description'),
        ('profile_app', '0003_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('fio', models.CharField(max_length=50, verbose_name='fio')),
                ('delivery_type', models.CharField(choices=[('express', 'express'), ('ordinary', 'ordinary')], default='ordinary', max_length=20, verbose_name='delivery_type')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('someone', 'someone')], default='online', max_length=20, verbose_name='payment_type')),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('canceled', 'canceled')], default='unpaid', max_length=20, verbose_name='payment_status')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='total_amount')),
                ('payment_id', models.CharField(max_length=50, verbose_name='payment_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order_app.order', verbose_name='order_item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.product', verbose_name='product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='profile_app.seller', verbose_name='seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
